root: true
env:
  browser: true
  es6: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  p5: true
  createGraphics: true
  drawingContext: true
  width: true
  height: true
  image: true
  P2D: true
ignorePatterns:
  - "**/build/**/*"
  - "**/examples/**/*"
  - "**/tests/**/*"
  - "**/*.min.js"
