root: true
env:
  browser: true
  es6: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  p5: true
  createGraphics: true
  drawingContext: true
  width: true
  height: true
  image: true
  translate: true
  rotate: true
  scale: true
  P2D: true
ignorePatterns:
  - build
  - dist
  - node_modules
  - out
  - gh-pages
  - "**/build/**/*"
  - "**/examples/**/*"
  - "**/tests/**/*"
  - "**/*.min.js"
overrides:
  - files:
      - "**/jsdoc.js"
    globals:
      module: true
